/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BossesModal: typeof import('./src/components/modals/BossesModal.vue')['default']
    BossGuess: typeof import('./src/components/panels/guesses/BossGuess.vue')['default']
    BossGuessCounts: typeof import('./src/components/panels/guesses/BossGuessCounts.vue')['default']
    BossGuessDamage: typeof import('./src/components/panels/guesses/BossGuessDamage.vue')['default']
    BossGuessRanges: typeof import('./src/components/panels/guesses/BossGuessRanges.vue')['default']
    BossGuessSouls: typeof import('./src/components/panels/guesses/BossGuessSouls.vue')['default']
    BossSearch: typeof import('./src/components/panels/search/BossSearch.vue')['default']
    Button: typeof import('./src/components/layout/Button.vue')['default']
    DamageBox: typeof import('./src/components/layout/DamageBox.vue')['default']
    FailedEffect: typeof import('./src/components/effects/FailedEffect.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GateOrnament: typeof import('./src/components/layout/ornaments/GateOrnament.vue')['default']
    GateOrnamentCenter: typeof import('./src/components/layout/ornaments/GateOrnamentCenter.vue')['default']
    GateOrnamentSingle: typeof import('./src/components/layout/ornaments/GateOrnamentSingle.vue')['default']
    GuessedEffect: typeof import('./src/components/effects/GuessedEffect.vue')['default']
    GuessesPanel: typeof import('./src/components/panels/guesses/GuessesPanel.vue')['default']
    Header: typeof import('./src/components/layout/Header.vue')['default']
    InstructionsModal: typeof import('./src/components/modals/InstructionsModal.vue')['default']
    KnownInfo: typeof import('./src/components/panels/KnownInfo.vue')['default']
    RecordsModal: typeof import('./src/components/modals/RecordsModal.vue')['default']
    SearchPanel: typeof import('./src/components/panels/search/SearchPanel.vue')['default']
    YharnamScreen: typeof import('./src/components/layout/YharnamScreen.vue')['default']
  }
}
